[project]
name = "educanopos"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "peewee>=3.18.1",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "ipython>=9.3.0",
    "pytest>=8.4.1",
]
